### PR TITLE
update eslint to 2.11.0

### PR DESCRIPTION
**Pull request by alanbsmith**
Heyo!

I followed your instructions in the readme and updated eslint to the latest version 2.11.0. Let me know if I need to do anything else, and thanks for providing this resource! super helpful!

### CODE REVIEW

**Comment by justinforce** [comment]
Wow! Thanks @alanbsmith! This warrants a major version bump of the gem to coincide with the major bump in ESLint.

**Comment by alanbsmith** [comment]
Yep! I think this is the only real tool for linting React / JSX in Rails, and this update should allow that to happen.

**Comment by justinforce** [comment]
@alanbsmith Looks like there is no v2.11.0 of ESLint. I tried to figure out the version that you provided, but I can't find it in there. I'm going to just update this gem to the latest ESLint release.

**Comment by alanbsmith** [comment]
oh, that should be 2.3.0. sorry.

**Comment by justinforce** [comment]
It's all good. I superceded this with #12. I'll release the gem shortly.

**Comment by alanbsmith** [comment]
thanks!

**Comment by justinforce** [comment]
The new version is released as `1.0.0`! Thanks again!

**Comment by alanbsmith** [comment]
yep! thanks for the update!

**Pull request closed without merging**
