### PR TITLE
adds rake task for running ESLint against directories

### PR DESCRIPTION
**Pull request by alanbsmith**
### OVERVIEW
This PR adds a rake task that allows users to run ESLint against a particular directory instead of a single file. If no directory is chosen, it uses the `app` directory by default.

### SPECIFICS
I've added some comments to my work to help clarify what's happening. But here are the steps:
* determine whether a directory has been given as an argument and get its path
* find and properly format the paths of each Javascript file in the directory and subdirectories
  * this will include JSX, JSON, and JS.ERB
* iterate over each of the paths and essentially perform the `run` task with each filename

### QUESTIONS
* **Should `application.js` be removed from the list of files to lint?**
  * It takes a long time to lint, and most of the code external
* **Why not call the `run` task with  `Rake::Task["eslint:run"].invoke(filename)`?**
  * This is a good question, and I'm not opposed to that idea. But the current `run` task breaks the execution of the `run_dir` task, so it would need to be altered.
* **This _feels like_ a lot of logic in a rake task. Why not create another method in `runner.rb`?**
  * Definitely not opposed to that idea. Would like some feedback though.
* **Should be one 'smart' rake task (`run`) to handle either directories or specific files?**
  * Would it be slick to have "one task to rule them all™"? Sure.
  * Should the concerns be separated? ... Probably.
  * I can see both sides of this argument. 
* **Why couldn't you come up with a better name than `run_dir`?**
  * I need more coffee, but I'm open to name changes.

### VERIFICATION
Hook the gem up to a Rails repo and run it!
Try both `rake eslint:run_dir[some_directory_name]` and `rake eslint:run_dir`

### CLOSING & THANKS
I'm definitely open to feedback and am willing to change whatever you want. I feel like this functionality could really help the gem be a more useful tool overall. Thanks again for your effort to create and maintain this tool. I think it's super useful and would like to continue helping it improve. Cheers!

### CODE REVIEW

**Comment by dkniffin** [comment]
@justinforce Any chance this is going to get merged soon?

**Comment by justinforce** [comment]
@dkniffin I'm very sorry, but I don't work for AppFolio anymore. Maybe @jonkessler can help out?

**Comment by jonkessler** [comment]
Yes, I'll try to get to this soon.

**Comment by jonkessler** [comment]
@alanbsmith I tend to prefer the route that @dkniffin has taken in #22 rather than adding a new task. As such, I'm planning to close this. Let me know if you have any objection to that.

**Pull request closed without merging**
